title: An Evolution of Statistics
description: The Art of Learning from Data.

# Build settings
remote_theme: "mmistakes/minimal-mistakes@4.28.0"
plugins:
  - jekyll-include-cache
  - jekyll-feed

minimal_mistakes_skin: "neon"

atom_feed:
  hide: true

# author
author:
  name     : "Pablo Strunz"
  avatar   : "assets/images/starry_night_hike.png"
  bio      : "Thinking out loud about Data Science."
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/cian-ps"

# Defaults
defaults:
  # _posts
  - scope:
      path: "_posts"
      type: posts
    values:
      layout: single
      show_date: true

markdown: kramdown
kramdown:
  math_engine: mathjax

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - notebooks/
  - .pyspelling.yml
  - wordlist.dic
  - .wordlist.txt
  - custom_nbconvert.py
  - nbconvert.sh
